### ISSUE TITLE
Research what would be the smallest Transformer model to test lifecycle assumptions on

### ISSUE THREAD

**Issue by janchk** [aifoundry-org/ainekko#8]
Hey team, I propose we settle on BERT embeddings as documented here. Please review https://github.com/aifoundry-org/.github/wiki/Notes-on-llama.cpp-and-distributed-engine-archtecture#debuggingcontrol-flow

**Comment by janchk** [comment]
Probably https://github.com/karpathy/nanoGPT should be considered.

**Comment by rvs** [comment]
One of the requirement I should've put onto this is that the model should be available in the gguf format and inferenceable on ggml and/or llama.cpp. How much work do you think it will be to convert nanoGPT to these requirements?

**Comment by janchk** [comment]
Pretty easy. So nanoGPT with potential fallback into Bert should be fine.
